### ISSUE TITLE
Can't download

### ISSUE THREAD

**Issue by DmytroGDnext** [GDNext-GmbH/polybpmn#1]
I found your plugin description on polybpmn.com.
But can't find extended version on Marketplace. 
Could you please provide a correct URL?

**Comment by VHavrylenko** [comment]
Hello @DmytroGDnext 
Here is correct link to download plugin https://plugins.jetbrains.com/plugin/21361-polybpmn-visualizer

**Comment by DmytroGDnext** [comment]
Amazing! Many thanks.
